namespace ATS.Services.EmailAccounts;

/// <summary>
/// Builds the <c>ISecretProtector</c> context that binds a stored app password to the account
/// it belongs to.
/// </summary>
/// <remarks>
/// Defined in one place because protect and unprotect must agree exactly: a context that
/// differs by a character produces a decryption failure at send time, in a background job, long
/// after the write that caused it.
///
/// Bound to the mailbox rather than the primary key for two reasons. The key is generated by
/// the database, so binding to it would mean inserting the row, reading the id back and
/// updating the password in a second write - a window in which the row exists with an
/// unprotected or empty password. And the mailbox is already in the set of fields whose change
/// forces the password to be re-entered, so a rename can never leave a ciphertext bound to a
/// context that no longer exists.
/// </remarks>
public static class AtsEmailAccountSecrets
{
	// Case-insensitive on purpose: SMTP mailboxes are, and a row saved as "Ops@cibi.com" must
	// still decrypt when the selector reads it back as "ops@cibi.com".
	public static string PasswordContext(string emailAddress) =>
		$"ats.EmailAccounts.EncryptedPassword:{emailAddress.Trim().ToLowerInvariant()}";
}
