services:
  apigateway:
    container_name: apigateway
    image: apigateway
    env_file:
      - .env
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  apis:
    container_name: oneplatform-backend
    image: ${DOCKER_REGISTRY-}apis
    env_file:
      - .env
    build:
      context: .
      dockerfile: BackendAPI/API/APIs/Dockerfile

  # frontendwebassembly:
  #   profiles: ["docker"]
  #   container_name: oneplatform-frontend
  #   image: ${DOCKER_REGISTRY-}frontendwebassembly
  #   build:
  #     context: ./UI/FrontendWebassembly
  #     dockerfile: /Dockerfile

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
