namespace ATS.Data.EntityConfiguration;

public class AtsEmailSendLogConfiguration : IEntityTypeConfiguration<AtsEmailSendLog>
{
	public void Configure(EntityTypeBuilder<AtsEmailSendLog> builder)
	{
		builder.ToTable("EmailSendLog", "ats");

		builder.HasKey(x => x.AtsEmailSendLogId);

		// Generated by the database rather than in code: this is an append-only counter table
		// written once per successful send, and nothing needs the id before the insert.
		builder.Property(x => x.AtsEmailSendLogId)
			   .ValueGeneratedOnAdd();

		builder.Property(x => x.AtsEmailAccountId)
			   .IsRequired();

		builder.Property(x => x.RecipientCount)
			   .IsRequired();

		builder.Property(x => x.SentAt)
			   .IsRequired();

		// Cascade: consumption history has no meaning once the account it belongs to is gone,
		// and leaving orphans behind would make the retention sweep the only thing that ever
		// removes them.
		builder.HasOne<AtsEmailAccount>()
			   .WithMany()
			   .HasForeignKey(x => x.AtsEmailAccountId)
			   .OnDelete(DeleteBehavior.Cascade);

		// The only read shape: SUM(RecipientCount) for one account over the last 24 hours,
		// asked once per message. Covers the retention sweep's range delete as well.
		builder.HasIndex(x => new { x.AtsEmailAccountId, x.SentAt });
	}
}
