// <auto-generated />
using System;
using ATS.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIs.Migrations.ATS
{
    [DbContext(typeof(ATSDBContext))]
    [Migration("20260605083105_IncreasedMaxLengthToAllEntityATSMigration")]
    partial class IncreasedMaxLengthToAllEntityATSMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ATS.Data.Entities.AddressDetails", b =>
                {
                    b.Property<Guid>("Address")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CurrentCity")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CurrentCountry")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CurrentPostalCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CurrentProvince")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CurrentStayFrom")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CurrentTypeOfOwnership")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PermanentCity")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PermanentCountry")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PermanentPostalCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PermanentProvince")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PermanentTypeOfOwnership")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Address");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("AddressDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.DocumentDetails", b =>
                {
                    b.Property<Guid>("DocumentDetailsID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DocumentValue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentDetailsID");

                    b.HasIndex("EmailInvitationID");

                    b.ToTable("DocumentDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.EducationalBackground", b =>
                {
                    b.Property<Guid>("EducationalBackgroundID")
                        .HasColumnType("uuid");

                    b.Property<string>("BachelorsAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BachelorsDegree")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BachelorsDiplomaFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("BachelorsGraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("BachelorsMajor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BachelorsSchoolName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CollegeAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CollegeDegree")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CollegeDiplomaFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("CollegeGraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("CollegeMajor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CollegeSchoolName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorateAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DoctorateDegree")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DoctorateDiplomaFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("DoctorateGraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("DoctorateMajor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("HighSchoolAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HighSchoolDiplomaFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("HighSchoolGraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("HighSchoolName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HighestEducationalAttainment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MastersAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MastersDegree")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MastersDiplomaFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("MastersGraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("MastersMajor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MastersSchoolName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhDSchoolName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SchoolSpecificLOAFileKey")
                        .HasColumnType("text");

                    b.Property<string>("SeniorHighSchoolAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SeniorHighSchoolDiplomaFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("SeniorHighSchoolGraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("SeniorHighSchoolName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("EducationalBackgroundID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("EducationalBackground", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.EmailInvitationRequest", b =>
                {
                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HashToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("HashTokenCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HashTokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MiddleInitial")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RushNormal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SelectPackage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("EmailInvitationID");

                    b.ToTable("EmailInvitationRequest", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.LicensesDetails", b =>
                {
                    b.Property<Guid>("LicensesDetailsID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("LicenseExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("LicenseName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LicenseUploadFileKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LicensesDetailsID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("LicensesDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.PersonalDetails", b =>
                {
                    b.Property<Guid>("PersonalID")
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalGovtIDFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailAlternative")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NBIClearanceFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhilSysImageKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PositionAppliedFor")
                        .HasColumnType("text");

                    b.Property<string>("ResumeFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SSS")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sex")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TIN")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("PersonalID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("PersonalDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.ProfessionalExperiences", b =>
                {
                    b.Property<Guid>("ProfessionalExperiencesID")
                        .HasColumnType("uuid");

                    b.Property<string>("COEUploadFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Emp1COEUploadFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp1CompanyAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp1CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp1CurrentlyEmployed")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("Emp1EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Emp1JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp1PermissionToContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp1ReasonForLeaving")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("Emp1StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Emp1SupervisorContactNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp1SupervisorEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp1SupervisorName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp2COEUploadFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp2CompanyAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp2CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp2CurrentlyEmployed")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("Emp2EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Emp2JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp2PermissionToContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp2ReasonForLeaving")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("Emp2StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Emp2SupervisorContactNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp2SupervisorEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp2SupervisorName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp3COEUploadFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp3CompanyAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp3CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp3CurrentlyEmployed")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("Emp3EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Emp3JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp3PermissionToContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp3ReasonForLeaving")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("Emp3StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Emp3SupervisorContactNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp3SupervisorEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Emp3SupervisorName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ProfessionalExperiencesID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("ProfessionalExperiences", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.ReferenceDetails", b =>
                {
                    b.Property<Guid>("ReferenceDetailsID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Ref1AffiliatedCompany")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("Ref1BestTimeToContact")
                        .HasMaxLength(255)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ref1ContactNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref1Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref1FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref1ModeOfContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref1ProfessionalRelationship")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref2AffiliatedCompany")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("Ref2BestTimeToContact")
                        .HasMaxLength(255)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ref2ContactNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref2Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref2FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref2ModeOfContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref2ProfessionalRelationship")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref3AffiliatedCompany")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("Ref3BestTimeToContact")
                        .HasMaxLength(255)
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ref3ContactNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref3Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref3FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref3ModeOfContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ref3ProfessionalRelationship")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ReferenceDetailsID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("ReferenceDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.SignatureDetails", b =>
                {
                    b.Property<Guid>("SignatureDetailsID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("SignatureDate")
                        .HasColumnType("date");

                    b.Property<string>("SignatureFileKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SignerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SignatureDetailsID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("SignatureDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.AddressDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("AddressDetails")
                        .HasForeignKey("ATS.Data.Entities.AddressDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.DocumentDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithMany("Documents")
                        .HasForeignKey("EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.EducationalBackground", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("EducationalBackground")
                        .HasForeignKey("ATS.Data.Entities.EducationalBackground", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.LicensesDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("LicensesDetails")
                        .HasForeignKey("ATS.Data.Entities.LicensesDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.PersonalDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("PersonalDetails")
                        .HasForeignKey("ATS.Data.Entities.PersonalDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.ProfessionalExperiences", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("ProfessionalExperiences")
                        .HasForeignKey("ATS.Data.Entities.ProfessionalExperiences", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.ReferenceDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("ReferenceDetails")
                        .HasForeignKey("ATS.Data.Entities.ReferenceDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.SignatureDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("SignatureDetails")
                        .HasForeignKey("ATS.Data.Entities.SignatureDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.EmailInvitationRequest", b =>
                {
                    b.Navigation("AddressDetails");

                    b.Navigation("Documents");

                    b.Navigation("EducationalBackground");

                    b.Navigation("LicensesDetails");

                    b.Navigation("PersonalDetails");

                    b.Navigation("ProfessionalExperiences");

                    b.Navigation("ReferenceDetails");

                    b.Navigation("SignatureDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
