// <auto-generated />
using System;
using ATS.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIs.Migrations.ATS
{
    [DbContext(typeof(ATSDBContext))]
    partial class ATSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ATS.Data.Entities.AddressDetails", b =>
                {
                    b.Property<Guid>("Address")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrentCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrentCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrentPostalCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrentProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrentStayFrom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrentTypeOfOwnership")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentPostalCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PermanentTypeOfOwnership")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Address");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("AddressDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.DocumentDetails", b =>
                {
                    b.Property<Guid>("DocumentDetailsID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentDetailsID");

                    b.HasIndex("EmailInvitationID");

                    b.ToTable("DocumentDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.EducationalBackground", b =>
                {
                    b.Property<Guid>("EducationalBackgroundID")
                        .HasColumnType("uuid");

                    b.Property<string>("BachelorsAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BachelorsDegree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BachelorsDiploma")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BachelorsGraduationDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BachelorsMajor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BachelorsSchoolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CollegeAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CollegeDegree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CollegeDiploma")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CollegeGraduationDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CollegeMajor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CollegeSchoolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoctorateAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DoctorateDegree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DoctorateDiploma")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DoctorateGraduationDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DoctorateMajor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("HighSchoolAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HighSchoolDiploma")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HighSchoolGraduationDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HighSchoolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HighestEducationalAttainment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MastersAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MastersDegree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MastersDiploma")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MastersGraduationDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MastersMajor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MastersSchoolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhDSchoolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("SchoolSpecificLOA")
                        .HasColumnType("bytea");

                    b.Property<string>("SeniorHighSchoolAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SeniorHighSchoolDiploma")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SeniorHighSchoolGraduationDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SeniorHighSchoolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EducationalBackgroundID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("EducationalBackground", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.EmailInvitationRequest", b =>
                {
                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HashToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("HashTokenCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("HashTokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleInitial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RushNormal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SelectPackage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("EmailInvitationID");

                    b.ToTable("EmailInvitationRequest", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.LicensesDetails", b =>
                {
                    b.Property<Guid>("LicensesDetailsID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("LicenseExpiryDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LicenseName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("LicenseUpload")
                        .HasColumnType("bytea");

                    b.HasKey("LicensesDetailsID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("LicensesDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.PersonalDetails", b =>
                {
                    b.Property<Guid>("PersonalID")
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalGovtID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailAlternative")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NBIClearance")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Resume")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SSS")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sex")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Suffix")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TIN")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PersonalID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("PersonalDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.ProfessionalExperiences", b =>
                {
                    b.Property<Guid>("ProfessionalExperiencesID")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("COEUpload")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Emp1CompanyAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1CurrentlyEmployed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1EndDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1PermissionToContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1ReasonForLeaving")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1StartDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1SupervisorContactNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1SupervisorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp1SupervisorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2CompanyAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2CurrentlyEmployed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2EndDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2PermissionToContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2ReasonForLeaving")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2StartDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2SupervisorContactNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2SupervisorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp2SupervisorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3CompanyAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3CurrentlyEmployed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3EndDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3PermissionToContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3ReasonForLeaving")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3StartDate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3SupervisorContactNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3SupervisorEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Emp3SupervisorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ProfessionalExperiencesID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("ProfessionalExperiences", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.ReferenceDetails", b =>
                {
                    b.Property<Guid>("ReferenceDetailsID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailInvitationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Ref1AffiliatedCompany")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref1BestTimeToContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref1ContactNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref1Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref1FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref1ModeOfContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref1ProfessionalRelationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref2AffiliatedCompany")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref2BestTimeToContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref2ContactNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref2Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref2FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref2ModeOfContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref2ProfessionalRelationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref3AffiliatedCompany")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref3BestTimeToContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref3ContactNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref3Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref3FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref3ModeOfContact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ref3ProfessionalRelationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ReferenceDetailsID");

                    b.HasIndex("EmailInvitationID")
                        .IsUnique();

                    b.ToTable("ReferenceDetails", "ats");
                });

            modelBuilder.Entity("ATS.Data.Entities.AddressDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("AddressDetails")
                        .HasForeignKey("ATS.Data.Entities.AddressDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.DocumentDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithMany("Documents")
                        .HasForeignKey("EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.EducationalBackground", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("EducationalBackground")
                        .HasForeignKey("ATS.Data.Entities.EducationalBackground", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.LicensesDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("LicensesDetails")
                        .HasForeignKey("ATS.Data.Entities.LicensesDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.PersonalDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("PersonalDetails")
                        .HasForeignKey("ATS.Data.Entities.PersonalDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.ProfessionalExperiences", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("ProfessionalExperiences")
                        .HasForeignKey("ATS.Data.Entities.ProfessionalExperiences", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.ReferenceDetails", b =>
                {
                    b.HasOne("ATS.Data.Entities.EmailInvitationRequest", null)
                        .WithOne("ReferenceDetails")
                        .HasForeignKey("ATS.Data.Entities.ReferenceDetails", "EmailInvitationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ATS.Data.Entities.EmailInvitationRequest", b =>
                {
                    b.Navigation("AddressDetails");

                    b.Navigation("Documents");

                    b.Navigation("EducationalBackground");

                    b.Navigation("LicensesDetails");

                    b.Navigation("PersonalDetails");

                    b.Navigation("ProfessionalExperiences");

                    b.Navigation("ReferenceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
